//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from AutumnQuery.g by ANTLR 4.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Autumn.Mvc.Models.Queries {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IAutumnQueryListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6")]
[System.CLSCompliant(false)]
public partial class AutumnQueryBaseListener : IAutumnQueryListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutumnQueryParser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelector([NotNull] AutumnQueryParser.SelectorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutumnQueryParser.selector"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelector([NotNull] AutumnQueryParser.SelectorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutumnQueryParser.eval"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEval([NotNull] AutumnQueryParser.EvalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutumnQueryParser.eval"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEval([NotNull] AutumnQueryParser.EvalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutumnQueryParser.or"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOr([NotNull] AutumnQueryParser.OrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutumnQueryParser.or"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOr([NotNull] AutumnQueryParser.OrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutumnQueryParser.and"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd([NotNull] AutumnQueryParser.AndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutumnQueryParser.and"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd([NotNull] AutumnQueryParser.AndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutumnQueryParser.constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstraint([NotNull] AutumnQueryParser.ConstraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutumnQueryParser.constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstraint([NotNull] AutumnQueryParser.ConstraintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutumnQueryParser.group"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroup([NotNull] AutumnQueryParser.GroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutumnQueryParser.group"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroup([NotNull] AutumnQueryParser.GroupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutumnQueryParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison([NotNull] AutumnQueryParser.ComparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutumnQueryParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison([NotNull] AutumnQueryParser.ComparisonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutumnQueryParser.comparator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparator([NotNull] AutumnQueryParser.ComparatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutumnQueryParser.comparator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparator([NotNull] AutumnQueryParser.ComparatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutumnQueryParser.comp_fiql"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComp_fiql([NotNull] AutumnQueryParser.Comp_fiqlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutumnQueryParser.comp_fiql"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComp_fiql([NotNull] AutumnQueryParser.Comp_fiqlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutumnQueryParser.comp_alt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComp_alt([NotNull] AutumnQueryParser.Comp_altContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutumnQueryParser.comp_alt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComp_alt([NotNull] AutumnQueryParser.Comp_altContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutumnQueryParser.reserved"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReserved([NotNull] AutumnQueryParser.ReservedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutumnQueryParser.reserved"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReserved([NotNull] AutumnQueryParser.ReservedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutumnQueryParser.single_quote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingle_quote([NotNull] AutumnQueryParser.Single_quoteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutumnQueryParser.single_quote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingle_quote([NotNull] AutumnQueryParser.Single_quoteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutumnQueryParser.double_quote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDouble_quote([NotNull] AutumnQueryParser.Double_quoteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutumnQueryParser.double_quote"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDouble_quote([NotNull] AutumnQueryParser.Double_quoteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutumnQueryParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArguments([NotNull] AutumnQueryParser.ArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutumnQueryParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArguments([NotNull] AutumnQueryParser.ArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutumnQueryParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] AutumnQueryParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutumnQueryParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] AutumnQueryParser.ValueContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Autumn.Mvc.Models.Queries
